---
title: "CASE STUDY 3"
author: "Ted Smith"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(gapminder)
library(ggplot2)
library(dplyr)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
data <- gapminder

```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!

Distinct <- data %>% 
  distinct(country, continent) %>% 
  group_by(continent) %>% 
  count(continent)

names(Distinct) = c("Continent", "CountryCount")

Distinct

PopYear <- data %>% 
  group_by(year) 

PopYear <- aggregate(PopYear$pop, by=list(year=PopYear$year), FUN=sum)
  
names(PopYear) = c("Year", "Population")

PopYear




NoKU <- data %>% 
  filter(country != 'Kuwait')

NoKU


```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

## Qualitative
G1 <- ggplot(data = Distinct,
             mapping = aes(x = Continent,
                           y = CountryCount,
                           fill = Continent)) +
  geom_col() +
  theme_bw()+
  labs(x = 'Continent',
       y = 'Number of Countries',
       title = 'Number of Countries Per Continent',
       subtitle = 'Case Study 3',
       caption = 'Qualitative')

G1
G1Save <- ggsave("G1.png", width = 15, units = "in")



## Quantitative
G2 <- ggplot(data = PopYear,
             mapping = aes(x = Year,
                           y = Population)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = c(1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002, 2007)) +
  scale_y_continuous(breaks = c(3000000000, 4000000000, 5000000000, 6000000000), labels = c(3, 4, 5, 6)) +
  labs(y = "Population (Billion)",
       x = "Year",
       title = "World Population per Year",
       subtitle = "Case Study 3",
       caption = 'Quantitative') +
  theme_light()
  

G2
G2Save <- ggsave("G2.png", width = 15, units = "in")


#Bivariate
G3 <- ggplot(data = NoKU,
             mapping = aes(x = year,
                           y = gdpPercap,
                           fill = continent)) +
  
  geom_col() +
  labs(x = 'Year',
  y = 'GDP Per Capita',
  title = 'GDP of Each Continent',
  subtitle = 'Case Study 3',
  caption = 'Bivariate' ) +
  scale_x_continuous(breaks = c(1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002, 2007)) +
  scale_y_continuous(breaks = c(250000, 500000, 750000, 1000000, 1250000, 1500000)) +
  theme_light()
               
G3
G3Save <- ggsave("G3.png", width = 15, units = "in")

## Life Exp vs. GDP
G4 <- ggplot(data = NoKU,
       mapping = aes(x = lifeExp,
                     y = gdpPercap,
                     color = continent,
                     size = pop)) +
  scale_y_continuous(trans = "sqrt") +
  theme_bw() +
  geom_point() +
  facet_wrap(~year, nrow = 1) +
  #Labels
  labs(x = "Life Expectancy",
                y = "GDP Per Capita",
                title = "A Look at Life Expectancy and GDP Per Capita*",
                subtitle = "Case Study 3",
                caption = "*Sans Kuwait",
                color = "Continent",
                size = "Population (100k)") +
  scale_size_area(breaks = c(250000000,500000000,750000000,1000000000,1250000000), labels = c(2500, 5000, 7500, 10000, 12500))

G4






G4Save <- ggsave("G4.png", width = 15, units = "in")
        
  

```

## Conclusions
