---
title: "Task 6"
author: "TedSmith"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(readr)
library(ggplot2)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
rcw <- read_csv("https://byuistats.github.io/M335/data/rcw.csv", #Pulling in the csv to use.
                col_types = cols(Semester_Date = col_date(format = "%m/%d/%y"), #
                                 Semester = col_factor(levels = c("Winter", "Spring", "Fall"))))
```

## Background

_Place Task Background Here_

## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
head(rcw) #Shows the first few rows of each column of the dataset rcw
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!
ggplot(data = rcw, 
       mapping = aes(x = Semester_Date, 
                     y = Count, 
                     color = Department)) +
  geom_line() +
  geom_point()    #line graph using the dataset rcw showing 'semester_date' on the x-axis and 'count' on the y-axis. The color of the graph is depicting what 'department' is shown.
                  #geom_point is adding points to the graph


ggplot(data = rcw,
       mapping = aes(x = Department,
                     y = Count,
                     color = Department)) +
  geom_bar(stat='identity')

```

## Conclusions
